### ISSUE TITLE
What should be default for 'version' ?

### ISSUE THREAD

**Issue by paulvi** [open-archetypes/tycho-eclipse-plugin-archetype#21]
First build fails. What should be default for 'version' ?

```
Define value for property 'groupId': : org.nodeclipse
Define value for property 'artifactId': : buildmasteride
Define value for property 'version':  1.0-SNAPSHOT: :
Define value for property 'package':  org.nodeclipse: : org.nodeclipse.bmi
[INFO] Using property: eclipse_platform = luna
[INFO] Using property: java_version = 1.8
[INFO] Using property: signing_support = false
[INFO] Using property: tycho_version = 0.22.0
Confirm properties configuration:
groupId: org.nodeclipse
artifactId: buildmasteride
version: 1.0-SNAPSHOT
package: org.nodeclipse.bmi
eclipse_platform: luna
java_version: 1.8
signing_support: false
tycho_version: 0.22.0
 Y: : y
[INFO] ----------------------------------------------------------------------------
[INFO] Using following parameters for creating project from Archetype: tycho-eclipse-plugin-archetype:1.0.0
[INFO] ----------------------------------------------------------------------------
[INFO] Parameter: groupId, Value: org.nodeclipse
[INFO] Parameter: artifactId, Value: buildmasteride
[INFO] Parameter: version, Value: 1.0-SNAPSHOT
[INFO] Parameter: package, Value: org.nodeclipse.bmi
[INFO] Parameter: packageInPathFormat, Value: org/nodeclipse/bmi
[INFO] Parameter: eclipse_platform, Value: luna
[INFO] Parameter: package, Value: org.nodeclipse.bmi
[INFO] Parameter: version, Value: 1.0-SNAPSHOT
[INFO] Parameter: groupId, Value: org.nodeclipse
[INFO] Parameter: java_version, Value: 1.8
[INFO] Parameter: tycho_version, Value: 0.22.0
[INFO] Parameter: signing_support, Value: false
[INFO] Parameter: artifactId, Value: buildmasteride
[INFO] Parent element not overwritten in D:\Workspaces\GitHub\buildmaster-ide\buildmasteride\buildmasteride.core\pom.xml
[INFO] Parent element not overwritten in D:\Workspaces\GitHub\buildmaster-ide\buildmasteride\buildmasteride.test\pom.xml
[INFO] Parent element not overwritten in D:\Workspaces\GitHub\buildmaster-ide\buildmasteride\buildmasteride.feature\pom.xml
[INFO] Parent element not overwritten in D:\Workspaces\GitHub\buildmaster-ide\buildmasteride\buildmasteride.site\pom.xml
[INFO] project created from Archetype in dir: D:\Workspaces\GitHub\buildmaster-ide\buildmasteride
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 02:40 min
[INFO] Finished at: 2017-10-20T00:01:43+08:00
[INFO] Final Memory: 15M/122M
[INFO] ------------------------------------------------------------------------

D:\Workspaces\GitHub\buildmaster-ide>start .

D:\Workspaces\GitHub\buildmaster-ide>cd buildmasteride

D:\Workspaces\GitHub\buildmaster-ide\buildmasteride>mvn install
[INFO] Scanning for projects...
[ERROR] Internal error: org.eclipse.tycho.core.osgitools.OsgiManifestParserException: Exception parsing OSGi MANIFEST D:\Workspaces\GitHub\buildmaster-ide\buildmasteride\buildmasteride.core\META-INF\MANIFEST.MF: Invalid manifest header Bundle-Version: "1.0.qualifier" : invalid version "1.0.qualifier": non-numeric "qualifier": For input string: "qualifier" -> [Help 1]
org.apache.maven.InternalErrorException: Internal error: org.eclipse.tycho.core.osgitools.OsgiManifestParserException: Exception parsing OSGi MANIFEST D:\Workspaces\GitHub\buildmaster-ide\buildmasteride\buildmasteride.core\META-INF\MANIFEST.MF: Invalid manifest header Bundle-Version: "1.0.qualifier" : invalid version "1.0.qualifier": non-numeric "qualifier"
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:121)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.eclipse.tycho.core.osgitools.OsgiManifestParserException: Exception parsing OSGi MANIFEST D:\Workspaces\GitHub\buildmaster-ide\buildmasteride\buildmasteride.core\META-INF\MANIFEST.MF: Invalid manifest header Bundle-Version: "1.0.qualifier" : invalid version "1.0.qualifier": non-numeric "qualifier"
        at org.eclipse.tycho.core.osgitools.OsgiManifest.<init>(OsgiManifest.java:50)
        at org.eclipse.tycho.core.osgitools.OsgiManifest.parse(OsgiManifest.java:152)
        at org.eclipse.tycho.core.osgitools.DefaultBundleReader.loadManifestFile(DefaultBundleReader.java:100)
        at org.eclipse.tycho.core.osgitools.DefaultBundleReader.loadManifestFromDirectory(DefaultBundleReader.java:96)
        at org.eclipse.tycho.core.osgitools.DefaultBundleReader.doLoadManifest(DefaultBundleReader.java:58)
        at org.eclipse.tycho.core.osgitools.DefaultBundleReader.loadManifest(DefaultBundleReader.java:49)
        at org.eclipse.tycho.core.osgitools.OsgiBundleProject.readArtifactKey(OsgiBundleProject.java:140)
        at org.eclipse.tycho.core.osgitools.OsgiBundleProject.setupProject(OsgiBundleProject.java:135)
        at org.eclipse.tycho.core.resolver.DefaultTychoResolver.setupProject(DefaultTychoResolver.java:74)
        at org.eclipse.tycho.core.maven.TychoMavenLifecycleParticipant.afterProjectsRead(TychoMavenLifecycleParticipant.java:72)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:266)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
        ... 11 more
Caused by: org.osgi.framework.BundleException: Invalid manifest header Bundle-Version: "1.0.qualifier" : invalid version "1.0.qualifier": non-numeric "qualifier"
        at org.eclipse.osgi.internal.resolver.StateBuilder.createBundleDescription(StateBuilder.java:100)
        at org.eclipse.osgi.internal.resolver.StateObjectFactoryImpl.createBundleDescription(StateObjectFactoryImpl.java:32)
        at org.eclipse.osgi.service.resolver.StateObjectFactory$StateObjectFactoryProxy.createBundleDescription(StateObjectFactory.java:558)
        at org.eclipse.tycho.core.osgitools.OsgiManifest.<init>(OsgiManifest.java:46)
        ... 23 more
Caused by: java.lang.IllegalArgumentException: invalid version "1.0.qualifier": non-numeric "qualifier"
        at org.osgi.framework.Version.parseInt(Version.java:170)
        at org.osgi.framework.Version.<init>(Version.java:134)
        at org.osgi.framework.Version.valueOf(Version.java:257)
        at org.osgi.framework.Version.parseVersion(Version.java:228)
        at org.eclipse.osgi.internal.resolver.StateBuilder.createBundleDescription(StateBuilder.java:96)
        ... 26 more
Caused by: java.lang.NumberFormatException: For input string: "qualifier"
        at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
        at java.lang.Integer.parseInt(Integer.java:580)
        at java.lang.Integer.parseInt(Integer.java:615)
        at org.osgi.framework.Version.parseInt(Version.java:168)
        ... 30 more
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/InternalErrorException
```

**Comment by paulvi** [comment]
The same error if entering version value `1.0`
